# Generated by Django 5.1.1 on 2024-11-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esqueceu_senha", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="email_paciente",
        ),
    ]
