# Generated by Django 5.1.2 on 2024-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0007_cadastroregistro_imagem_fundo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastroregistro",
            name="imagem_perfil",
            field=models.ImageField(
                blank=True,
                default="img/perfil-icon.png",
                null=True,
                upload_to="imagens_perfil/",
            ),
        ),
    ]
