# Generated by Django 5.1.2 on 2024-10-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0008_cadastroregistro_imagem_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastroregistro",
            name="imagem_fundo",
        ),
    ]
