# Generated by Django 5.1.3 on 2024-11-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0012_alter_cadastroregistro_tipo_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastroregistro",
            name="cpf_paciente",
            field=models.CharField(max_length=14),
        ),
    ]
