# Generated by Django 5.1.3 on 2024-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0013_alter_cadastroregistro_cpf_paciente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastroregistro",
            name="cpf_paciente",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
