# Generated by Django 5.1.3 on 2024-11-19 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0015_alter_cadastroregistro_user_perfil"),
        ("config", "0003_rename_user_perfil_cadastro_registro_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="cadastro_registro",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_perfil_paciente",
                to="cadastro_registro.cadastroregistro",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="config_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
