# Generated by Django 5.1.3 on 2024-11-20 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0017_alter_cadastroregistro_options_and_more"),
        ("config", "0005_alter_perfil_cadastro_registro_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={
                "verbose_name": "Perfil de Configuração",
                "verbose_name_plural": "Perfis de Configuração",
            },
        ),
        migrations.AlterField(
            model_name="perfil",
            name="acessibilidade",
            field=models.JSONField(
                default=dict, verbose_name="Configurações de Acessibilidade"
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="cadastro_registro",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_config",
                to="cadastro_registro.cadastroregistro",
                verbose_name="Cadastro Registro",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="config_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="imagem_perfil",
            field=models.ImageField(
                blank=True,
                default="img/perfil-icon.png",
                null=True,
                upload_to="perfil_imagens/",
                verbose_name="Imagem de Perfil",
            ),
        ),
    ]
