# Generated by Django 5.1.2 on 2024-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consulta", "0002_remove_consulta_assunto_remove_consulta_data_hora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="assunto",
            field=models.CharField(default="Sem assunto", max_length=200),
        ),
        migrations.AddField(
            model_name="consulta",
            name="email",
            field=models.EmailField(default="email@exemplo.com", max_length=254),
        ),
        migrations.AddField(
            model_name="consulta",
            name="nome",
            field=models.CharField(default="Nome Desconhecido", max_length=100),
        ),
        migrations.AddField(
            model_name="consulta",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="telefone",
            field=models.CharField(default="0000-0000", max_length=20),
        ),
    ]
