# Generated by Django 5.1.2 on 2024-10-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consulta", "0003_consulta_assunto_consulta_email_consulta_nome_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consulta",
            name="paciente",
        ),
    ]
