# Generated by Django 5.1.2 on 2024-10-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0009_remove_cadastroregistro_imagem_fundo"),
        ("consulta", "0005_alter_consulta_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="paciente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro_registro.cadastroregistro",
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="assunto",
            field=models.CharField(
                choices=[
                    ("CHECKUP", "Checkup Regular"),
                    ("LIMPEZA", "Limpeza Dental"),
                    ("EXTRACAO", "Extração de Dente"),
                    ("APARELHO", "Consulta para Aparelho"),
                ],
                max_length=50,
            ),
        ),
    ]
