# Generated by Django 5.1.2 on 2024-10-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consulta", "0006_consulta_paciente_alter_consulta_assunto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="assunto",
            field=models.CharField(
                choices=[
                    ("avaliacao_diagnostico", "Avaliação e Diagnóstico"),
                    ("tratamentos_restauradores", "Tratamentos Restauradores"),
                    ("tratamentos_periodontais", "Tratamentos Periodontais"),
                    ("odontopediatria", "Odontopediatria"),
                    ("ortodontia", "Ortodontia"),
                    ("odontologia_estetica", "Odontologia Estética"),
                    ("cirurgia_oral", "Cirurgia Oral"),
                    ("proteses_dentarias", "Próteses Dentárias"),
                    ("consultas_emergencia", "Consultas de Emergência"),
                    ("acompanhamento_manutencao", "Acompanhamento e Manutenção"),
                ],
                default="avaliacao_diagnostico",
                max_length=50,
            ),
        ),
    ]
