# Generated by Django 5.1.1 on 2024-11-04 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consulta", "0007_alter_consulta_assunto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="medico",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "medico"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
