# Generated by Django 5.1.3 on 2024-11-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consulta", "0008_consulta_medico"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="exame_realizado",
            field=models.BooleanField(default=False, verbose_name="Exame Realizado"),
        ),
    ]
