# Generated by Django 5.1.3 on 2024-11-25 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_registro", "0017_alter_cadastroregistro_options_and_more"),
        ("consulta", "0009_consulta_exame_realizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="avaliacao_cavidade",
            field=models.TextField(
                blank=True, null=True, verbose_name="Avaliação da Cavidade Bucal"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="cirurgias_anteriores",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cirurgias Anteriores"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="condicoes_saude",
            field=models.TextField(
                blank=True, null=True, verbose_name="Condições de Saúde Geral"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="diagnostico_detalhado",
            field=models.TextField(
                blank=True, null=True, verbose_name="Diagnóstico Detalhado"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="documento_identificacao",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Documento de Identificação",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="endereco_contato",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Endereço e Contato"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="genero",
            field=models.CharField(
                choices=[
                    ("masculino", "Masculino"),
                    ("feminino", "Feminino"),
                    ("outro", "Outro"),
                ],
                default="masculino",
                max_length=20,
                verbose_name="Gênero",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="historico_tratamentos",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Histórico de Tratamentos Odontológicos",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="lesoes_anomalias",
            field=models.TextField(
                blank=True, null=True, verbose_name="Presença de Lesões ou Anomalias"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="nome_paciente",
            field=models.CharField(
                default="Nome Desconhecido",
                max_length=255,
                verbose_name="Nome Completo do Paciente",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="procedimentos_planejados",
            field=models.TextField(
                blank=True, null=True, verbose_name="Procedimentos Planejados"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="queixas_principais",
            field=models.TextField(
                blank=True, null=True, verbose_name="Queixas Principais do Paciente"
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="paciente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro_registro.cadastroregistro",
            ),
        ),
    ]
